<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FTITMHH4" ignored="0" name="Test" tests="2" failures="1" timestamp="2021-09-04T15:55:53 ICT" time="57.069" errors="0">
  <testcase name="test" time="21.332" classname="qaautomation.august2021.App">
    <failure type="java.lang.AssertionError" message="expected [fullstackdemo] but found [fullstackdemofailed]">
      <![CDATA[java.lang.AssertionError: expected [fullstackdemo] but found [fullstackdemofailed]
at qaautomation.august2021.App.test(App.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test1" time="9.239" classname="qaautomation.august2021.App"/>
</testsuite> <!-- Test -->
